### ISSUE TITLE
java.io.NotSerializableException: com.svenjacobs.reveal.RevealCanvasState

### ISSUE THREAD

**Issue by lehmansnDev** [svenjacobs/reveal#89]
**Describe the bug**
The exception only occurs rarely. So far it has only occurred when starting the app.
Unfortunately, I can't say much more about the problem.
If you other information, please feel free to ask.

**Expected behavior**
```
FATAL EXCEPTION: main
    Process: de.lehmansn.birthdays, PID: 29604
    android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = [First Screen])
    	at android.os.Parcel.writeSerializable(Parcel.java:2797)
    	at android.os.Parcel.writeValue(Parcel.java:2563)
    	at android.os.Parcel.writeValue(Parcel.java:2362)
    	at android.os.Parcel.writeList(Parcel.java:1415)
    	at android.os.Parcel.writeValue(Parcel.java:2506)
    	at android.os.Parcel.writeValue(Parcel.java:2362)
    	at android.os.Parcel.writeList(Parcel.java:1415)
    	at android.os.Parcel.writeValue(Parcel.java:2506)
    	at android.os.Parcel.writeValue(Parcel.java:2362)
    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1298)
    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
    	at android.os.Bundle.writeToParcel(Bundle.java:1389)
    	at android.os.Parcel.writeBundle(Parcel.java:1367)
    	at android.os.Parcel.writeValue(Parcel.java:2479)
    	at android.os.Parcel.writeValue(Parcel.java:2369)
    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1298)
    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
    	at android.os.Bundle.writeToParcel(Bundle.java:1389)
    	at android.os.Parcel.writeBundle(Parcel.java:1367)
    	at android.os.Parcel.writeValue(Parcel.java:2479)
    	at android.os.Parcel.writeValue(Parcel.java:2369)
    	at android.os.BaseBundle.dumpStats(BaseBundle.java:1917)
    	at android.os.BaseBundle.dumpStats(BaseBundle.java:1954)
    	at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:123)
    	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:139)
    	at android.os.Handler.handleCallback(Handler.java:958)
    	at android.os.Handler.dispatchMessage(Handler.java:99)
    	at android.os.Looper.loopOnce(Looper.java:205)
    	at android.os.Looper.loop(Looper.java:294)
    	at android.app.ActivityThread.main(ActivityThread.java:8177)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
    Caused by: java.io.NotSerializableException: com.svenjacobs.reveal.RevealCanvasState
    	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
    	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
    	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
    	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
    	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
    	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
    	at android.os.Parcel.writeSerializable(Parcel.java:2792)
    	at android.os.Parcel.writeValue(Parcel.java:2563) 
    	at android.os.Parcel.writeValue(Parcel.java:2362) 
    	at android.os.Parcel.writeList(Parcel.java:1415) 
    	at android.os.Parcel.writeValue(Parcel.java:2506) 
    	at android.os.Parcel.writeValue(Parcel.java:2362) 
    	at android.os.Parcel.writeList(Parcel.java:1415) 
    	at android.os.Parcel.writeValue(Parcel.java:2506) 
    	at android.os.Parcel.writeValue(Parcel.java:2362) 
    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1298) 
    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843) 
    	at android.os.Bundle.writeToParcel(Bundle.java:1389) 
    	at android.os.Parcel.writeBundle(Parcel.java:1367) 
    	at android.os.Parcel.writeValue(Parcel.java:2479) 
    	at android.os.Parcel.writeValue(Parcel.java:2369) 
    	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1298) 
    	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843) 
    	at android.os.Bundle.writeToParcel(Bundle.java:1389) 
    	at android.os.Parcel.writeBundle(Parcel.java:1367) 
    	at android.os.Parcel.writeValue(Parcel.java:2479) 
    	at android.os.Parcel.writeValue(Parcel.java:2369) 
    	at android.os.BaseBundle.dumpStats(BaseBundle.java:1917) 
    	at android.os.BaseBundle.dumpStats(BaseBundle.java:1954) 
    	at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:123) 
    	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:139) 
    	at android.os.Handler.handleCallback(Handler.java:958) 
    	at android.os.Handler.dispatchMessage(Handler.java:99) 
    	at android.os.Looper.loopOnce(Looper.java:205) 
    	at android.os.Looper.loop(Looper.java:294) 
    	at android.app.ActivityThread.main(ActivityThread.java:8177) 
    	at java.lang.reflect.Method.invoke(Native Method) 
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
```

**Smartphone (please complete the following information):**
 - Device: Google Pixel 8
 - Android version:  Android 14

**Comment by lehmansnDev** [comment]
I have analyzed it further.
It happens when my smartphone is locked and I start the app from my IDE.
The deployment is finished and I am unlocking my smartphone. Then the exception is thrown.
It's not that bad, it's not a real scenario for users.

**Comment by svenjacobs** [comment]
That's interesting, thanks @lehmansnDev. Are you somehow putting a `RevealCanvasState` in a `rememberSaveable`? Because that  is actually not supported.

**Comment by lehmansnDev** [comment]
Okay, good to know.
But I don't put it into a `rememberSavable`. It is just a parameter of the screen.
Maybe it is because I am using [Voyager](https://github.com/adrielcafe/voyager).

```
setContent {
        val revealCanvasState = rememberRevealCanvasState()
        val birthdaysScreen = rememberScreen(SharedScreen.Birthdays(revealCanvasState))

        BirthdaysTheme {
            RevealCanvas(
                modifier = Modifier.fillMaxSize(),
                revealCanvasState = revealCanvasState,
            ) {
                Navigator(birthdaysScreen) { navigator ->
                    SlideTransition(navigator)
                }
            }
        }
}
```

I would close the issue, because it is not really an issue for me.
Is that fine for you?

**Comment by svenjacobs** [comment]
I will close this ticket because it seems to not affect apps in production.

**Comment by lehmansnDev** [comment]
Hey Sven,
The error occurs more often than I thought.
Whenever I put the app in the background, the exception is thrown.
It's due to Voyager, it only allows parameters that can be [serialized](https://voyager.adriel.cafe/state-restoration). 
I think `RevealCanvasState` is not serializable, so the app crashes at that moment.
Is it possible to make `RevealCanvasState` serializable?

**Comment by svenjacobs** [comment]
@lehmansnDev I wonder how Voyager can force `RevealCanvasState` to be serialized when we only use `remember` and not `rememberSaveable`? Anyway, since `RevealCanvasState` contains a lambda I need to check if it's even possible to serialize this class. Is there no way in Voyager to exclude a class from serialization? Could you maybe post some example code?

**Comment by svenjacobs** [comment]
Hello @lehmansnDev, did you see my questions above?

**Comment by svenjacobs** [comment]
Okay, now I understand. You're passing `RevealCanvasState` into the constructor of a `Screen` implementation. So this is not strictly happening in a Compose context.

Please see the solution [here](https://github.com/adrielcafe/voyager/issues/59#issuecomment-1113346218). Can you try putting a `@Transient` to the `RevealCanvasState` argument?

However since the value is not restored by serialization, you might have the problem that Reveal isn't working anymore after the Voyager state was restored. You could store the instance of `RevealCanvasState` outside of Compose as a global variable and use it as a default value for the argument or ditch the constructor argument and straightforwardly use the global var. But I would have to open the constructor of the class because currently it is `internal` only.

**Comment by svenjacobs** [comment]
I just released version [3.0.5](https://github.com/svenjacobs/reveal/releases/tag/v3.0.5) where I opened the constructors. It make take a while until it's available on Maven Central. Please check if the proposed solution above is working for you.

**Comment by lehmansnDev** [comment]
Nice, thank you @svenjacobs.
I like your solution 👍

**Comment by svenjacobs** [comment]
Great, closing it! 🙂
